# The relative path to the main file / entry point.
main="main.bfpp"

# All outputs listed will be generated on build.
# Allowed values: "zig", "bf"
outputs=["zig"]

## All options below are optional and set here to the default values.

# options in [common] apply to all outputs.
# These options can be written in the other
# sections to override for individual outputs.
[common]
include_comments = true
include_formatting = true

# Options for generating a zig project.
[zig]
args=[] # Args for the zig compiler
build_after_template = true
launch_after_build = true
cell_size = 1 # in bytes
#   Certain failures which would stop execution by default
#   can be ignored. Failures would simply not modify the tape.
# ignore_error = [
#     "findExternFunction",
#     "createExternCaller"
# ]

# Options for outputing a single processed .bfpp file.
[bf]
include_debug_operators=true
compact_operators=true # use numerable operators and for loops

[launch]
# Args for the compiled output
args=[]